### ISSUE TITLE
Bangs probably don't do what you think

### ISSUE THREAD

**Issue by tomjaguarpaw** [valderman/selda#1]
These bangs probably don't do what you think:

https://github.com/valderman/selda/blob/4ad9fa4c21efa568d922bf3a3c0b87352763abf1/selda/src/Database/Selda/Query/Type.hs#L33-L36

They merely force the list to be evaluated to a cons or a nil.  They don't even force the head of the list let alone any of the other elements.

**Comment by valderman** [comment]
I know. However, applying strictness to the first cons prevents thunks from building up when repeatedly modifying a value without forcing it. Without any strictness, repeatedly applying a function `f` to the field results in a bunch of nested thunks `f (f (f (f ...)))` which may in extreme cases overflow the evaluation stack, and can cause noticeable slowdown long before that.

**Comment by tomjaguarpaw** [comment]
It seems extremely implausible to me that ! on list-valued fields could be the difference between a problem and no problem.  Do you have an example?

**Comment by valderman** [comment]
Indeed, it'd take quite the pathological case for those annotations to actually make an appreciable difference here - pathological enough that I can't really come up with a sensible function that would cause a problem (though if you were to repeatedly reverse the list... :). Worst case scenario, strictness won't make any difference either way, so the choice is pretty arbitrary.

**Comment by tomjaguarpaw** [comment]
Can you come up with an *un*sensible function?  I'd be interested to see literally *any* situation where that bang pattern makes a difference.

**Comment by valderman** [comment]
Yes: `undefined`. I'd rather have the code explode immediately if something that nonsensical were to happen, then have laziness move the error somewhere else. Another example would be repeatedly reversing the list. In *all* cases, you save (modulo optimizations which may or may not kick in) one thunk per operation. Considering that Haskell programs in general allocate memory like it's going out of fashion, any reduction in generated garbage is a good thing. Especially when it has no downsides.

**Comment by tomjaguarpaw** [comment]
If those issues really are so important then why not go for full spine-strict lists?

There is a downside and that is that the ! *looks* terribly important when in practice is serves hardly any purpose.  A *minor* performance improvement, perhaps.  As I see it there are two better options:

1. Remove the ! for a massive decrease in confusion and tiny performance hit

2. Use ! with spine strict lists, maybe even spine *and* value strict lists.

**Comment by tomjaguarpaw** [comment]
Didn't actually mean to close that issue, but it doesn't really matter ...

**Comment by valderman** [comment]
I guess we disagree about the gravity of the presence of a bang, then.

**Comment by tomjaguarpaw** [comment]
I wouldn't describe its presence as *grave*.  Just if you think it's important to have, which it seems you do, why not take it to its logical conclusion with a spine strict list?

**Comment by valderman** [comment]
I don't really care that much about it, I'm just in the habit of making things strict unless there's a reason for them not to be. A stricter data structure would probably be better here, yes, but would the difference be great enough to merit the additional complexity? I'm not sure, and then it's very easy to err on the side of least resistance. :)
