### ISSUE TITLE
Select if value exists in a list

### ISSUE THREAD

**Issue by reygoch** [valderman/selda#110]
Is it possible to select only values that are in the list? There is `isIn` function but it's only geared towards static length query results, right? I'd like to do something like:

```haskell
restrict $ category ! #name `isIn` literal ["name01", "name02", ...]
```

**Comment by valderman** [comment]
No, `isIn` is overloaded and should work for queries as well. Assuming that `category ! #name` is a text column and that `names` is a table with a single text column (i.e. `Table (Only Text)` You should be able to do this:
```
restrict $ category ! #name `isIn` (the <$> select names)
```
