### ISSUE TITLE
Consider using type-errors package for better error messages

### ISSUE THREAD

**Issue by luc-tielen** [valderman/selda#119]
As mentioned in the first paragraph on https://selda.link/tutorial/, type errors can be daunting at times.

This could potentially be solved by using the [type-errors](https://hackage.haskell.org/package/type-errors) package to make error messages easier to understand (and maybe even give a clue on how to fix certain type errors).

An example of something that could be done is as follows: https://github.com/cdepillabout/world-peace/pull/5, blog post with more info can be found  [here](https://kodimensional.dev/type-errors).

**Comment by valderman** [comment]
We already do custom errors for illegal return types, and as of 3e0a99d2c10407fb56644c26e1bf57393951fa20 (due for release in 0.4.1.0) we'll also have them for scope violations.

Are there any other errors that are particularly egregious where domain-specific errors would be helpful? I can't think of any off the top of my head, but I'm getting bit blind to the bad errors at this point so I'm definitely the best source of bad errors.

**Comment by luc-tielen** [comment]
Well, I've only been trying it out for simple scenario's so far, but the tutorial I linked previously gave me the impression that there are a lot of places with complex type errors. 
Maybe consider rewording the tutorial page and/or putting something along the lines of "a bad/complex type error is considered a bug and should be reported" so any potentially difficult errors are phased out over time?
