### ISSUE TITLE
Logo, slogan?

### ISSUE THREAD

**Issue by dmjio** [valderman/selda#12]
cc @valderman 

Slogan
> _"The best Haskell database library in all of Hyrule"_

😄

Logo
![hyrule-logo-t-shirt](https://cloud.githubusercontent.com/assets/875324/25307542/7af1ed7a-2757-11e7-813f-1d8529cdc229.png)
Reference
![hyrule-logo-t-shirt-1](https://cloud.githubusercontent.com/assets/875324/25307543/7af82500-2757-11e7-9486-eac9e0e3a2b7.png)

**Comment by valderman** [comment]
I went ahead and used your suggested logo (though I redid it for higher resolution) for the new [website](https://selda.link). Countdown to C&D starts now, I guess. :)

**Comment by dmjio** [comment]
@valderman, this is so dope. Well done.

**Comment by dmjio** [comment]
@valderman, The `.link` TLD is a nice touch as well ;)

**Comment by dmjio** [comment]
Well done sir. 🍺
