### ISSUE TITLE
SeldaT is not an instance of MonadTrans

### ISSUE THREAD

**Issue by lortabac** [valderman/selda#120]
Apparently since 4514ec0390941c136fd8c4837452202c41b404a1 `SeldaT` is not an instance of `MonadTrans` anymore.

Has that instance been removed on purpose? Or is it a mistake?

**Comment by valderman** [comment]
No, it seems it got lost while experimenting with ways to parameterise SeldaT over a backend. The end result should be just as MonadTrans-like as before the parameterisation so this instance should be brought back ASAP. Thanks for spotting it!

**Comment by valderman** [comment]
Fixed as of 2fad97b9944bfbf84cac384369ebc263db17552f.
