### ISSUE TITLE
compileCreateTable is no longer public

### ISSUE THREAD

**Issue by anisjonischkeit** [valderman/selda#123]
Hey,

I was using compileCreateTable to show the create scripts that would be needed to get the tables that the application is expecting but it seems to have been made private in 0.4.0.0. What was the reason behind this?

**Comment by valderman** [comment]
The `compile*` functions were moved to [Database.Selda.Debug](https://hackage.haskell.org/package/selda-0.4.0.0/docs/Database-Selda-Debug.html), as part of a move to reduce the amount of clutter you get when importing `Database.Selda` and making it a bit more discoverable. Sorry for the inconvenience.

**Comment by anisjonischkeit** [comment]
All good, makes sense. Thanks for letting me know :)
