### ISSUE TITLE
"if not exists" misplaced in create index

### ISSUE THREAD

**Issue by paolino** [valderman/selda#126]
I've updated to 0.4.0.0, create index doesn't work anymore at least with sqlite backend.

From [sqlite create index docs](https://sqlite.org/lang_createindex.html) the **if not exists** part  should be placed before the **on** part but it's placed after, so I get syntax errors on **create index** statement.

Same goes for postgresql [create index docs](https://www.postgresql.org/docs/10/sql-createindex.html), but this I didn't test.

[relevant code](https://github.com/valderman/selda/blob/a92107242a437431150260f70b9242653931777d/selda/src/Database/Selda/Table/Compile.hs#L84)

[commit](https://github.com/valderman/selda/commit/8386b3d5a3912b93f544bdaf9ddc67d22e1eb18f)

**Comment by valderman** [comment]
Fixed as of 4a536a5391e914cf95bdb83a87a208cc21ff1f05.
