### ISSUE TITLE
Only "pure selda" in latest stakgage snapshot 

### ISSUE THREAD

**Issue by majkrzak** [valderman/selda#141]
I've noticed that in the https://www.stackage.org/lts-16.0 there is only selda selda package and the rest are missing. Rest got stuck on: https://www.stackage.org/lts-14.27

**Comment by valderman** [comment]
Thanks for notifying me, this completely flew under my radar!

Dependency bounds have been updated and there's now a [PR to re-add the missing packages](https://github.com/commercialhaskell/stackage/pull/5514).

**Comment by valderman** [comment]
PR has been merged, so the everything should be back in the nightlies shortly and should go into the next LTS.

**Comment by majkrzak** [comment]
Looks, like it is only in nightly. It is missing in every single LTS 16.x.
https://github.com/commercialhaskell/stackage/blob/lts16/build-constraints.yaml#L3576-L3577
