### ISSUE TITLE
How to remove column from table

### ISSUE THREAD

**Issue by Spaubleit** [valderman/selda#142]
Hello. Thank you for this great library. I have one question. How to remove column from table during migration? There is new function for creation but I could not find corresponding function for removal.

**Comment by valderman** [comment]
To remove a column, simply create your new table type without that column.

```haskell
data Foo_V1 = Foo_V1
{ a :: Int
, b :: Int
}

data Foo_V2 = Foo_V2
{ aPlusB :: Text
}

foo_v1 :: Table Foo_V1
foo_v1 = table ...

foo_v2 :: Table Foo_V2
foo_v2 = table ...

theMigration = migrate foo_v1 foo_v2 (\old -> new [ #aPlusB := (old ! #a) + (old ! #b) ])
```
Unfortunately, the migrations are a bit clunky as they require both a source and a target type to be present. I have some ideas about how to get rid of this restriction without losing type safety, but I'm still working out the details.

**Comment by Spaubleit** [comment]
Thank you! More detailed documentation would definitely help with understanding.
