### ISSUE TITLE
How to do "insert or ignore"?

### ISSUE THREAD

**Issue by GitKKg** [valderman/selda#144]
just find no way to do this operation, insert will just fail if you get one row violates unique constraint.
Also I tried the leftJoin to do except operation between two sets, but it seems no way to express unique id .== NULL,if use literal False, you always get [ ]  :

```
-- not get you want
query  $ do
                   -- tempSPt get same definition with stockPriceT, just get different table name
                    sR <-select tempSPt
                    ssR <- leftJoin (\rC -> (rC ! #_code .== sR ! #_code) .&& (rC ! #_date .== sR ! #_date)  ) 
                     (do
                             ssdata <-select stockPriceT
                             restrict $ literal False
                              return ssdata
                               )
                   return ssR

```
```

**Comment by valderman** [comment]
You can use [`tryInsert`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda.html#v:tryInsert) to insert or ignore. However, like `insert`, if you're inserting multiple rows at the same time, either all rows will be inserted, or none will.

There is currently no primitive that is semantically equivalent to `ON CONFLICT IGNORE`, but until that's implemented you can use [some unsafe magic](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda-Unsafe.html) to implement it by hand:
```haskell
rawStm $ "INSERT INTO my_table (first, second) VALUES (" <> injLit value1 <> ", " <> injLit value2 <> ") ON CONFLICT IGNORE"
```

As for null comparisons, I'm not entirely sure what you're trying to do. If you just want to check whether a field is null, you can use [`isNull`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda.html#v:isNull), but I'm guessing you want to do something a bit more complex than that?

**Comment by GitKKg** [comment]
Indeed ,finally I used tryInsert like this:
`num <- runSeldaT (do
                       tryCreateTable stockPriceT
                       boolL <- traverse ((tryInsert stockPriceT) . (: [])) stockData
                       return . DL.length . (DL.filter (\x -> x == True) ) $  boolL

                   )
                                              
                   
         pgCon
  logOutM $ "inserted " ++ show num ++ " rows into stock table\n"`

it seems to work well after test.
I never noticed rawStm this interface before, will give a try.

Thanks!
