### ISSUE TITLE
get TableName from Table

### ISSUE THREAD

**Issue by cdepillabout** [valderman/selda#147]
There doesn't appear to be any way to get a [`TableName`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda-Backend.html#t:TableName) from a `Table` (unless I'm just missing the function that does this).

My suggestion would be to add a `TableName` field to [`TableInfo`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda-Backend.html#t:TableInfo), so that you can get a `Table`'s `TableName` with the [`tableInfo`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda-Backend.html#v:tableInfo) function.

----------------------------------------

My reason for wanting this is as follows.

I am trying to construct a raw query string that I can pass to [`rawQuery`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda-Unsafe.html#v:rawQuery).  

I want to generate the table name from the `Table` definition.  This is so that if I ever change the table name, I only have to change it in one place (the `Table` definition), instead of two places, the `Table` definition and the raw query string.

**Comment by valderman** [comment]
How about we add a `tableName` field to the [`TableInfo`](https://hackage.haskell.org/package/selda-0.5.1.0/docs/Database-Selda-Backend.html#t:TableInfo) type? It sounds like the natural place for this.
