### ISSUE TITLE
Resource-pool based transformer

### ISSUE THREAD

**Issue by TomMD** [valderman/selda#160]
Selda's PSQL operation encourages a single connection for the lifetime of a monad.  I had other needs and made a resource-pool based monad transformer.  This could be upstreamed but judging by the pro-minimalistic language you'd favor having it in a separate package.  Thoughts?

**Comment by seanhess** [comment]
@TomMD Personally I think an example on the website somewhere would be enough. I'd be happy to provide one if it's helpful, or I'm sure you have one
