### ISSUE TITLE
Update selda packages on Hackage

### ISSUE THREAD

**Issue by DaQuirm** [valderman/selda#178]
Could you publish the packages with the latest changes (ghc 9.2 support etc.) on Hackage?
Thank you!

**Comment by DaQuirm** [comment]
NB: The new packages can already be consumed directly from github:
https://cabal.readthedocs.io/en/3.8/cabal-project.html#specifying-packages-from-remote-version-control-locations

**Comment by valderman** [comment]
Sorry for taking so long with this; now 0.5.2.0 is finally on Hackage.

**Comment by DaQuirm** [comment]
Tack så mycket! 👍
