### ISSUE TITLE
How to use `tableFieldMod`?

### ISSUE THREAD

**Issue by tankorsmash** [valderman/selda#185]
Thanks for the library, the docs are a big improvement over other ORMs!

[The docs list `autoFieldGen`](https://hackage.haskell.org/package/selda-0.5.2.0/docs/Database-Selda.html#v:tableFieldMod) as a way to rename a field, but I don't see `autoFieldGen` in the source anywhere.

Maybe there's an updated solution, but I've got 

```hs
data Person {
  personId: ID Person
}
```
 and I'd like to use the database column name "id" instead of "personId". I thought this is what `tableFieldMod` would be, but I'm not sure.

**Comment by tankorsmash** [comment]
Ah I think the docs are just out of date. Commit 3061213 shows a snippet:

```hs
modPeople :: Table Person
modPeople = tableFieldMod "modpeople" [name :- primary] $ \name ->
  "mod_" <> name
```
 and doing something like this for my case (remembering that `name` here is each of the columns, not just one) works!

**Comment by valderman** [comment]
Yeah, the docs are outdated here. That should be `autoPrimary`, not `autoPrimaryGen`, and the solution you found sounds like the correct one. A simple renaming function for your case might look like:
```
personColumnNames :: Text -> Text
personColumnNames "personId" = "id"
personColumnNames name = name
```
And then you'd do something like this to use it:
```
peopleTable :: Table Person
peopleTable = tableFieldMod "people" [#personId :- autoPrimary] personColumnNames
```
You'll also need to add a `deriving Generic` to your `Person` type (which requires the `DeriveGeneric` extension), an explicit `instance SqlRow Person` (the default instance for `SqlRow` should work as long as you derive `Generic` and don't use too exotic types for the fields of `Person`), and the `OverloadedLabels` extension for `#personId`.

**Comment by tankorsmash** [comment]
Thank you for breaking it down! That makes a lot of sense and lines up with the bits I was able to use on the official tutorial. Thanks!
