### ISSUE TITLE
More disciplined error handling

### ISSUE THREAD

**Issue by valderman** [valderman/selda#19]
Currently, backends just throw whichever exceptions they feel like and expect the user to just deal with it somehow. Instead, the backend API should provide a (very small) well-documented set of exceptions, and backends should restrict themselves to *only* throw those exceptions.

This also applies to table validation. If some aspect of a table isn't controlled by the type system, an `error` is thrown as soon as the table is evaluated. While we shouldn't encourage developers to actually catch this error and do something with it (in this situation, the program *should* explode, loudly and irrecoverably, as the schema is simply broken beyond repair), it would still be useful to throw a specific exception instead.

**Comment by dmjio** [comment]
@valderman would table validation happen at runtime? Or does this imply using TH to inspect the schema (like `relational-record`).

**Comment by valderman** [comment]
@dmjio at least for now, this happens at runtime, whenever the table is first evaluated. I guess it would be possible to do it using TH, but in that case I'd like to keep TH validation behind a configuration flag that defaults to off.

**Comment by valderman** [comment]
Fixed as of version 0.1.3.2.
