### ISSUE TITLE
Is the "Updating Rows" Section Correct?

### ISSUE THREAD

**Issue by aspidites** [valderman/selda#2]
![2017-04-20-173717_1015x313_scrot](https://cloud.githubusercontent.com/assets/93686/25253724/2224bfaa-25f0-11e7-8544-05f494fa0f19.png)

Given the text in the screenshot, I'd expect to see the order of the functions flipped. That is, the first function appears to be filtering out those persons whose name is Link, but the text says "The first is a mapping over table columns", which appears to be what the _second_ function here is doing.

**Comment by aspidites** [comment]
Actually, I just checked the types in the documentation, the example is correct, but the text seems to be wrong.

**Comment by valderman** [comment]
Fixed by 825a9c2220bc130ff13f67a116182b92416b9d0b.
