### ISSUE TITLE
Multiple primary keys

### ISSUE THREAD

**Issue by phaazon** [valderman/selda#25]
This is standard design for databases and I failed to see how I could have ones with selda.

**Comment by valderman** [comment]
Not sure I'm following. Having multiple primary keys (as in, having two separate `PRIMARY KEY` constraints) is not allowed by any database I know of. Are you referring to PKs that span multiple columns, for instance `CREATE TABLE foo (a INT, b INT) PRIMARY KEY (a, b)`?

There's currently no way to do this in Selda, but there's also technical reason it shouldn't be possible. The main issue is coming up with a nice syntax for it. Any suggestions for what sort of syntax would work well for this?

**Comment by phaazon** [comment]
I’m talking about the constraints. A constraint of type `PRIMARY KEY` can refer 1 to N columns – hence, tuples. I think the current limitation is linked to one problem:

- when you specify a column, you explicitely express it via a qualifier (`primary`, `autoPrimary`, `required`, `optional`, etc.); this could be fine if the constrains were of the same types, but they’re note. Primary keys constraints are referential constraints while required and optional are integrity constraints.

I think a good design would be to remove the primary key constructs (and use `required` instead), and then specify the primary keys at another place, like:

```haskell
myTable :: Table (RowID :*: Text :*: Maybe Float)
myTable = table (autoPrimary ["t_id", "t_text"]) $ required "t_id" :*: required "t_text" :*: optional "t_density"
```

Or something like that.

**Comment by nboldi** [comment]
This would be a nice feature.

**Comment by valderman** [comment]
Supported in all backends as of 252d8cbc1c19638fba73cd8c62f1fd89f776b89b.
