### ISSUE TITLE
Support for UUID primary keys in PostgreSQL

### ISSUE THREAD

**Issue by devlinzed** [valderman/selda#47]
I was wondering if this feature exists or is planned.  I took a look at the code and it doesn't look like it would be very hard to handle the UUID type, but UUID primary keys (and foreign keys) seem more complicated.

(Thanks a lot for the awesome library, I'm really enjoying working with it!)

**Comment by valderman** [comment]
I don't think UUID PKs or FKs would pose a problem; they should work for UUIDs without modification if we just add an UUID type. Or am I missing something?

Auto-"incrementing" (or rather, auto-generating) UUID PKs may require relaxing the type of `autoPrimary` slightly, but that'd probably be a good idea anyway.

**Comment by devlinzed** [comment]
I have no idea what I'm talking about, but I think that `RowID` would need to be changed to be polymorphic?

**Comment by devlinzed** [comment]
Hey @valderman, if you think this change would be valuable and can give me a pointer about where to start, I can try to dig in to this.  I really enjoy working with Selda (thanks again!) and think this would be a useful feature.
