### ISSUE TITLE
Function to validate database schema

### ISSUE THREAD

**Issue by ludat** [valderman/selda#50]
First of all, thank you very much for this awesome library.

I was thinking about having a function to check that the database has a table, for example I'd like to be certain that some table exists before I get my application up, I suppose it's not too much work, if I can make myself some time I'll implement it but I'd like to get your feedback.

**Comment by valderman** [comment]
This does indeed sound like useful functionality. Do you have any particular uses in mind except checking that the table exists and perhaps that it has an appropriate type?

**Comment by ludat** [comment]
Not really, I just want to avoid having runtime issues caused by broken migrations, nothing besides that really

**Comment by valderman** [comment]
As of db981671877168d75bbc8591bbf4890da1f98433, `validateTable` explicitly verifies the internal properties of a table. The idea is to make this function validate the table against a database as well, but this is not yet implemented.
