### ISSUE TITLE
Create a combinator that switches off foreign key checking

### ISSUE THREAD

**Issue by nboldi** [valderman/selda#57]
I created a development version of my application that automatically drops the tables on startup and re-creates them to work correctly when my schema changes. However I ran into SQL exceptions when I introduced foreign keys. The problem was that by dropping a table that is referenced from another one, the foreign key checker triggered.

I propose a combinator that temporary switches off the foreign key check to do such migration operations. It should be used like this:

```haskell
cleanDatabase = withForeignCheckTurnedOff $ do
   tryDropTable table1
   createTable table1
   -- ...
                                             
```

I've written a simple version of it for sqlite using the Selda backend. It might need to be defined differently to also work with other backends:

```haskell
withForeignCheckTurnedOff :: (MonadMask m, MonadIO m, MonadThrow m) => SeldaT m a -> SeldaT m a
withForeignCheckTurnedOff act = do
   backend <- Backend.seldaBackend
   (resCode, _) <- liftIO $ Backend.runStmt backend (pack "PRAGMA foreign_keys = OFF") [] -- TODO: something different for postgre
   when (resCode /= 0) (throwM $ Backend.SqlError "withForeignCheckTurnedOff: Switching foreign keys off was not successful.") 
   res <- act
   (resCode, _) <- liftIO $ Backend.runStmt backend (pack "PRAGMA foreign_keys = ON") []
   when (resCode /= 0) (throwM $ Backend.SqlError "withForeignCheckTurnedOff: Switching foreign keys back on was not successful.") 
   return res
```

**Comment by valderman** [comment]
Implementing this for PostgreSQL was surprisingly tricky, but I think this can go into the next release in the form of `withoutForeignKeyEnforcement`. In addition to turning off foreign key checking, this also runs the entire computation as a transaction to ensure that the hack used to implement this for PostgreSQL doesn't mess up the database.

**Comment by alexmingoia** [comment]
`withoutForeignKeyEnforcement` is not necessary, and negatively impacts performance by issuing a schema lock.

The correct way to deal with this is to use `DEFERRABLE ` foreign key constraints with `INITIALLY DEFERRED` as the default behavior, which defers foreign key constraints until the end of the transaction.

See PostgreSQL's documentation on `DEFERRABLE` and `INITIALLY DEFERRED`: https://www.postgresql.org/docs/current/sql-createtable.html or https://stackoverflow.com/a/16323708
