### ISSUE TITLE
BIGSERIAL SQL error

### ISSUE THREAD

**Issue by phaazon** [valderman/selda#60]
ERROR:  type "bigserial" does not exist

That type exists in PostgreSQL. I don’t get the error. Is there something specific to do on the `psql` side? That error occurs whenever I try to insert / query / whatever.

**Comment by phaazon** [comment]
[Might be related](https://www.postgresql.org/message-id/20050124140349.GB28988%40dcc.uchile.cl).

**Comment by valderman** [comment]
Do you have a minimal example which triggers this problem, along with the Selda and postgres version you're using? I've never encountered this before, so any additional information would be helpful in tracking it down.

**Comment by phaazon** [comment]
Ok, so, the patch would be to use `bigserial` _when declaring the type in the schema_, but use `bigint` in other places. I can work on that patch if you want.

**Comment by phaazon** [comment]
@valderman it’s from a work codebase, but I guess any code using `RowID` should fail on the postgres I’m using (PostgreSQL 10).

**Comment by phaazon** [comment]
Seems like this issue could benefit from #59!

**Comment by phaazon** [comment]
I have more hindsight  @valderman: I have the error on a `SQL CAST`.

**Comment by valderman** [comment]
If memory serves, the cast is probably the only non-schema part that mentions any types by name, so this should probably only need minor fix in `Print`. The API rejiggling mentioned in #59 would probably be the best way to fix this, but until that happens a fix for this particular issue is definitely needed. If you'd work on a patch for this, it'd be a great help.

**Comment by phaazon** [comment]
I’ll work on it then!

**Comment by phaazon** [comment]
I’m currently testing the patch on my production server.

**Comment by valderman** [comment]
Seems like there's more to the BIGSERIAL situation: foreign keys. Row identifiers should only be represented as BIGSERIAL if they're the _primary key_ of the table, otherwise they should be `BIGINT`. See [this SO question](https://stackoverflow.com/questions/25883982/can-a-serial-foreign-key-be-set-to-null) or [this test failure](https://travis-ci.org/valderman/selda/jobs/326869364), for instance.

So we'll need to take the fix a step further, or rather invert it: always use BIGINT _unless_ we're creating a table _and_ we're pretty-printing its primary key.

**Comment by phaazon** [comment]
Yeah, because of auto-incrementing aspect of `BIGSERIAL`, it doesn’t make any sense to use it in any otherplace than a *primary key*. We could default to `BIGINT` everywhere and have a special function for primary keys. I can alter the patch to have that, if you want.

**Comment by phaazon** [comment]
Are you on an IRC / gitter channel, so that it’s easier to communicate in real time?

**Comment by valderman** [comment]
Fixed by #63.

Oh, and I am on the gitter channel, but currently very sporadically due to other commitments so "real time" would likely be a bit of a misnomer I'm afraid.

**Comment by phaazon** [comment]
Duly noted. Thanks for the ultra fast reaction! <3
