### ISSUE TITLE
Optional fk on gen tables

### ISSUE THREAD

**Issue by NikitaRzm** [valderman/selda#77]
Hi! Thanks for such good library, really like it!
But i have a problem.

For example:
I have a table with self-reference fk, and by default this fk is always with `not null` constraint. Is there a way to make it optional? Cause now I cannot create category without parent.
I inspected sources of Generic module, but did not find any ways to add `optional` attribute to make field in gen table declaration optional.

Code:
Categories table with nested categories (fk on the same table, which defining now).
Purpose solution commented, not found any ways to do it. Maybe you know a workaround?

![image](https://user-images.githubusercontent.com/16317879/39698118-a86ee5d6-521d-11e8-8b7f-acfaa43943d0.png)

Thanks!

P.S. I can research and write some code in pr for this feature if there are no workaround and it is possible to implement without too much work.

**Comment by valderman** [comment]
In Selda, an optional field of type `a` is modeled as `Maybe a`, so you need to make `catParentId` a `Maybe RowID` rather than a `RowID`. Then you can do something like this:

```
data Foo = Foo
  { myId :: RowID
  , next :: Maybe RowID
  } deriving Generic

tbl :: GenTable Foo
tbl = genTable "foo"
  [ myId :- autoPrimaryGen
  , next :- fkGen (gen tbl) myIdSel
  ]

(myIdSel :*: nextSel) = selectors (gen tbl)
```

**Comment by NikitaRzm** [comment]
Thank you!

Already discovered that behaviour too, sorry for my inattention! :)
