### ISSUE TITLE
`make license` is not executed on OSX

### ISSUE THREAD

**Issue by lortabac** [valderman/selda#79]
Because the OSX filesystem is case-insensitive, the presence of a `LICENSE` file at the root of the project misleads `make`, which considers that the `license` target has already been executed.

This issue is particularly pernicious when using `stack`, because the missing file will cause it to fail with the unhelpful message:

```
/Users/me/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.0.2_ghc-8.2.1:
startProcess: invalid argument (Bad file descriptor)
```

Maybe `license` should be made .PHONY?

**Comment by valderman** [comment]
Good idea. In fact, almost all the targets in the makefile should really be `.PHONY`, come to think of it.
