### ISSUE TITLE
Raw sql query from template ?

### ISSUE THREAD

**Issue by checkraiser** [valderman/selda#82]
I have a bunch of sql template query files which need to run.
How to do it with Selda ?

**Comment by tungd** [comment]
Selda is a high level ORM/query builder, if you want to run raw SQL template  files you should look for lower level library like `postgresql-libpq` or `postgresql-simple`.

**Comment by valderman** [comment]
As @tungd says, you should use a lower level library if all you want to do is to run raw SQL. Selda doesn't support it, and would be massively overkill for the task even if it did.
