### ISSUE TITLE
GHC compilation fails on lengthy tables

### ISSUE THREAD

**Issue by ikv** [valderman/selda#86]
Using selda 0.1.12.1 from  lts-11.16

Compiling code with the `insert` call on a table of 12 cols or more results in a compilation failure:

```
ghc: panic! (the 'impossible' happened)
  (GHC version 8.2.2 for x86_64-unknown-linux):
        Simplifier ticks exhausted
  When trying UnfoldingDone lvl_s6jL
  To increase the limit, use -fsimpl-tick-factor=N (default 100)
  If you need to do this, let GHC HQ know, and what factor you needed
  To see detailed counts use -ddump-simpl-stats
  Total ticks: 86603
  Call stack:
      CallStack (from HasCallStack):
        prettyCurrentCallStack, called at compiler/utils/Outputable.hs:1133:58 in ghc:Outputable
        callStackDoc, called at compiler/utils/Outputable.hs:1137:37 in ghc:Outputable
        pprPanic, called at compiler/simplCore/SimplMonad.hs:199:31 in ghc:SimplMonad

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
```

Bumping  `-fsimpl-tick-factor` helps a little, at expense of increased compilation time. But anything in the range of 15+ cols requires prohibitive amounts of time and memory to compile.

Source code to reproduce:

```haskell
{-# LANGUAGE TypeOperators #-}
{-# LANGUAGE OverloadedStrings #-}
module Main where
import Database.Selda
import Database.Selda.SQLite


exampleTable :: Table
    (   Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int)
exampleTable = table "foo"
    $   required "a"
    :*: required "b"
    :*: required "c"
    :*: required "d"
    :*: required "e"
    :*: required "f"
    :*: required "g"
    :*: required "h"
    :*: required "i"
    :*: required "j"
    :*: required "k"
    :*: required "l"

main :: IO ()
main = withSQLite "example.sqlite" $ do
    insert_ exampleTable
        [1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1 :*: 1]
```

**Comment by valderman** [comment]
Good catch! Do you know if this happens only on inserts, or on other operations as well?

**Comment by ikv** [comment]
As far as i can tell selects are unaffected. But updates could be.

Updates compilation time is somewhat exponential of columns.
Same as inserts, but less severe.
On my i5-6200U 8Gb laptop compilation times is roughly the following:

* 36 cols - 24.5 seconds
* 26 cols - 12.5 seconds
* 22 cols - 9 seconds
* 12 cols - 4 seconds

code to play with:
```haskell
exampleTable :: Table
    (   Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int
    :*: Int)
exampleTable = table "foo"
    $   required "a"
    :*: required "b"
    :*: required "c"
    :*: required "d"
    :*: required "e"
    :*: required "f"
    :*: required "g"
    :*: required "h"
    :*: required "i"
    :*: required "j"
    :*: required "k"
    :*: required "l"

u :: SeldaM ()
u = transaction $
    update_
        exampleTable
        (\(a :*: b :*: c :*: d :*: e :*:f :*: g :*: h :*: i :*: j :*: k :*: l) ->
            a .== literal 0 .&&
            b .== literal 0 .&&
            c .== literal 0 .&&
            d .== literal 0 .&&
            e .== literal 0 .&&
            f .== literal 0 .&&
            g .== literal 0 .&&
            h .== literal 0 .&&
            i .== literal 0 .&&
            j .== literal 0 .&&
            k .== literal 0 .&&
            l .== literal 0
            )
        (\(a :*: b :*: c :*: d :*: e :*:f :*: g :*: h :*: i :*: j :*: k :*: l) ->
            (a+1 :*: b+1 :*: c+1 :*: d+1 :*: e+1 :*: f+1 :*: g+1 :*: h+1 :*: i+1 :*: j+1 :*: k+1 :*: l+1))
```

**Comment by valderman** [comment]
It looks like the problem doesn't occur with optimizations turned off. It also doesn't happen with GHC 7.10. It seems like the problem is with `table` and the way it's used by inserts and updates, as we don't even need to insert anything to trigger the problem:
```
main = withSQLite "example.sqlite" $ insert_ exampleTable  []
```

Furthermore, using a generic table will avoid the issue, but instead takes on the order of about a minute to compile (not all that surprising, considering that generic tables get translated into relations before being compiled):
```
data Foo = Foo Int Int Int Int Int Int Int Int Int Int Int Int
  deriving Generic

exT :: GenTable Foo
exT = genTable "foo" []

main :: IO ()
main = withSQLite "example.sqlite" $ insert_ (gen exT) []
```

This is hairy enough that the solution will likely be to (almost) entirely replace the `:*:` relations with something based on generics, at least for table definitions. It should probably be done anyway, to get a bit nicer, more type-safe queries, so I guess this may be a good thing in the long run, forcing us to make the switch sooner rather than later.

Of course, should anyone come up with a less invasive solution, I'd be all for implementing it in the meantime,

**Comment by ikv** [comment]
> It also doesn't happen with GHC 7.10.
Looks like upstream regression to me.

Are you in a mood to fill ghc bug?

**Comment by valderman** [comment]
As of 3061213, ad hoc tables are gone altogether, and generic tables have been reworked to more or less fix the issue with inserts (2½ seconds for 40 columns, with linear growth). Updates are still slow (though the slowdown seems to be closer to `n log n` than exponential - six seconds for 20 columns, 20 seconds for 40 columns), and I suspect the best way to fix this is to move towards allowing values to have types like `Col s User` to remove the tuples altogether.

I would submit a GHC bug report, but considering that a lot of reports about similar performance regressions have gotten closed with a _"well, you're doing it wrong, just don't do that thing that slows everything down"_, working on getting tuples out of the loop seems like a more productive use of time than trying to find a good minimal example.

**Comment by valderman** [comment]
Fixed (or at least as fixed as it's likely to get any time soon) as of 5a1ebed7ae5f7959f957a049917246d83c792dc6. Inserts and updates are still a bit slow to compile, but at least the pathological cases should be gone now.
