### ISSUE TITLE
Should we make `seldaConnection` minimal requirement for `MonadSelda`?

### ISSUE THREAD

**Issue by tungd** [valderman/selda#89]
Hi, I'm using Selda with Servant by implementing a `MonadSelda` instance. The class requires 'seldaConnection`, 'wrapTransaction` and `invalidateTable`, however I think the later two functions are only used when in-process caching is enabled? I can recall your answer from another ticket (also involve Servant) suggesting that.

I think we should add `{-# MINIMAL seldaConnection #-}` to `MonadSelda`, or provide a dummy/default implementation for those functions.

**Comment by valderman** [comment]
That seems reasonable, though perhaps with some modifications. While `invalidateTable` is perfectly OK to implement as a no-op if caching is not supported, `wrapTransaction` is needed for transactions. A reasonable default implementation (without caching support) could be given for any monad that implements `MonadMask`, but any other monad would have to roll their own (thread-unsafe) implementation.
