### ISSUE TITLE
SqlType for ADTs with fields

### ISSUE THREAD

**Issue by hojberg** [valderman/selda#97]
Sorry a little new to Haskell, so bare with me:

Is it possible to define a `SqlType` for ADTs that have fields (which means they can't be enums or bounded I believe).

Example of this would be:

```haskell
data due = Today | Scheduled Day | Unscheduled
```

**Comment by tungd** [comment]
If your type is `Enum` and `Bounded`, it just mean that it is qualified as a `SqlEnum`, which has a `SqlType` instance provided for you. However you can implement `SqlType` for any types, you just need to implement all the methods in the `SqlType` class. In your example you could piggy back on Aeson (I use `String` so it's easier to try out on GHCi):

```haskell
data Due = Today | Scheduled String | Unscheduled
  deriving (Show, Generic)

instance FromJSON Due
instance ToJSON Due

instance SqlType Due where
  -- Column type to store the field
  sqlType _ = TText

  -- How to convert Haskell value to SQL value for the column type specified in `sqlType`
  mkLit = LCustom . LText . TL.toStrict . encodeToLazyText

  -- How to convert SQL value back to Haskell value,
  -- could also use `defaultValue` instead partial function
  fromSql (SqlBlob blob) = fromMaybe (error "Unable to decode to Due value") (decodeStrict' blob)
  fromSql _              = error "Invalid column type for Due value"

  -- default
  defaultValue = LCustom (LBlob (encode Unscheduled))

```

This way the value will be stored as a text column using its JSON representation.

```haskell
> encode (Scheduled "next week")
"{\"tag\":\"Scheduled\",\"contents\":\"next week\"}"
> encode (Unscheduled)
"{\"tag\":\"Unscheduled\"}"
```

**Comment by hojberg** [comment]
@tungd I figured this was prolly possible in some way. This is awesome. Thank you!
